-- Migration: SEO Core
-- Adds SEO metadata fields to content and terms tables
-- Based on Foundry SEO Core specifications

-- ===================================
-- 1. ADD SEO FIELDS TO CONTENT TABLE
-- ===================================
ALTER TABLE content
-- Title & Description
ADD COLUMN IF NOT EXISTS seo_title TEXT,
ADD COLUMN IF NOT EXISTS seo_description TEXT,

-- Canonical
ADD COLUMN IF NOT EXISTS seo_canonical TEXT,

-- Robots directives
ADD COLUMN IF NOT EXISTS seo_robots_index BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS seo_robots_follow BOOLEAN DEFAULT true,

-- Focus keyword (for analysis)
ADD COLUMN IF NOT EXISTS seo_focus_keyword TEXT,

-- Open Graph
ADD COLUMN IF NOT EXISTS seo_og_title TEXT,
ADD COLUMN IF NOT EXISTS seo_og_description TEXT,
ADD COLUMN IF NOT EXISTS seo_og_image TEXT, -- URL or media path
ADD COLUMN IF NOT EXISTS seo_og_type TEXT DEFAULT 'article',

-- Twitter
ADD COLUMN IF NOT EXISTS seo_twitter_title TEXT,
ADD COLUMN IF NOT EXISTS seo_twitter_description TEXT,
ADD COLUMN IF NOT EXISTS seo_twitter_image TEXT,
ADD COLUMN IF NOT EXISTS seo_twitter_card TEXT DEFAULT 'summary_large_image' CHECK (seo_twitter_card IN ('summary', 'summary_large_image')),

-- Breadcrumbs override (optional)
ADD COLUMN IF NOT EXISTS seo_breadcrumb_title TEXT,

-- SEO Score (0-100, calculated)
ADD COLUMN IF NOT EXISTS seo_score INTEGER DEFAULT 0 CHECK (seo_score >= 0 AND seo_score <= 100);

-- Comments for documentation
COMMENT ON COLUMN content.seo_title IS 'Custom SEO title (fallback: title field)';
COMMENT ON COLUMN content.seo_description IS 'Custom meta description (fallback: excerpt)';
COMMENT ON COLUMN content.seo_canonical IS 'Canonical URL override (auto-generated by default)';
COMMENT ON COLUMN content.seo_robots_index IS 'Allow search engine indexing (default: true)';
COMMENT ON COLUMN content.seo_robots_follow IS 'Allow search engine to follow links (default: true)';
COMMENT ON COLUMN content.seo_focus_keyword IS 'Primary keyword for SEO analysis';
COMMENT ON COLUMN content.seo_score IS 'SEO score (0-100) based on automated analysis';

-- ===================================
-- 2. ADD SEO FIELDS TO TERMS TABLE
-- ===================================
ALTER TABLE terms
-- Title & Description
ADD COLUMN IF NOT EXISTS seo_title TEXT,
ADD COLUMN IF NOT EXISTS seo_description TEXT,

-- Canonical
ADD COLUMN IF NOT EXISTS seo_canonical TEXT,

-- Robots directives
ADD COLUMN IF NOT EXISTS seo_robots_index BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS seo_robots_follow BOOLEAN DEFAULT true,

-- Open Graph
ADD COLUMN IF NOT EXISTS seo_og_title TEXT,
ADD COLUMN IF NOT EXISTS seo_og_description TEXT,
ADD COLUMN IF NOT EXISTS seo_og_image TEXT,

-- Twitter
ADD COLUMN IF NOT EXISTS seo_twitter_title TEXT,
ADD COLUMN IF NOT EXISTS seo_twitter_description TEXT,
ADD COLUMN IF NOT EXISTS seo_twitter_image TEXT,
ADD COLUMN IF NOT EXISTS seo_twitter_card TEXT DEFAULT 'summary_large_image' CHECK (seo_twitter_card IN ('summary', 'summary_large_image'));

-- Comments for documentation
COMMENT ON COLUMN terms.seo_title IS 'Custom SEO title for taxonomy term (fallback: name)';
COMMENT ON COLUMN terms.seo_description IS 'Custom meta description for taxonomy term (fallback: description)';

-- ===================================
-- 3. CREATE SEO REDIRECTS TABLE
-- ===================================
CREATE TABLE IF NOT EXISTS seo_redirects (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    site_id UUID NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
    
    -- Redirect config
    source_path TEXT NOT NULL,
    destination_path TEXT NOT NULL,
    redirect_type INTEGER NOT NULL DEFAULT 301 CHECK (redirect_type IN (301, 302, 307, 308)),
    
    -- Status
    is_active BOOLEAN DEFAULT true,
    
    -- Stats (optional)
    hit_count INTEGER DEFAULT 0,
    last_hit_at TIMESTAMP WITH TIME ZONE,
    
    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Unique constraint: one source per site
    UNIQUE(site_id, source_path)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_seo_redirects_site_id ON seo_redirects(site_id);
CREATE INDEX IF NOT EXISTS idx_seo_redirects_source_path ON seo_redirects(site_id, source_path) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_seo_redirects_active ON seo_redirects(is_active);

-- Trigger for updated_at
CREATE TRIGGER update_seo_redirects_updated_at 
    BEFORE UPDATE ON seo_redirects
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Comments
COMMENT ON TABLE seo_redirects IS 'SEO redirects management (301, 302, 307, 308)';
COMMENT ON COLUMN seo_redirects.source_path IS 'Source path (without domain, e.g., /old-page)';
COMMENT ON COLUMN seo_redirects.destination_path IS 'Destination path or full URL';
COMMENT ON COLUMN seo_redirects.redirect_type IS 'HTTP redirect code (301 permanent, 302 temporary)';
COMMENT ON COLUMN seo_redirects.hit_count IS 'Number of times redirect was triggered';

-- ===================================
-- 4. CREATE SEO SETTINGS TABLE (GLOBAL)
-- ===================================
CREATE TABLE IF NOT EXISTS seo_settings (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    site_id UUID NOT NULL REFERENCES sites(id) ON DELETE CASCADE UNIQUE,
    
    -- Global SEO config
    site_name TEXT,
    site_tagline TEXT,
    site_description TEXT,
    separator TEXT DEFAULT '|' CHECK (separator IN ('|', '-', '–', '—', '/', '·')),
    
    -- Default title templates
    title_template_post TEXT DEFAULT '{{title}} | {{siteName}}',
    title_template_page TEXT DEFAULT '{{title}} | {{siteName}}',
    title_template_category TEXT DEFAULT '{{name}} | {{siteName}}',
    title_template_tag TEXT DEFAULT '{{name}} | {{siteName}}',
    title_template_home TEXT DEFAULT '{{siteName}} – {{tagline}}',
    
    -- Default meta
    default_og_image TEXT,
    default_twitter_card TEXT DEFAULT 'summary_large_image',
    
    -- Social accounts
    twitter_username TEXT,
    facebook_app_id TEXT,
    
    -- Knowledge Graph (Schema.org Organization)
    organization_name TEXT,
    organization_logo TEXT,
    
    -- Locale
    default_locale TEXT DEFAULT 'fr_FR',
    
    -- Sitemap config
    sitemap_posts_priority DECIMAL(2,1) DEFAULT 0.8 CHECK (sitemap_posts_priority >= 0.0 AND sitemap_posts_priority <= 1.0),
    sitemap_posts_changefreq TEXT DEFAULT 'weekly' CHECK (sitemap_posts_changefreq IN ('always', 'hourly', 'daily', 'weekly', 'monthly', 'yearly', 'never')),
    sitemap_pages_priority DECIMAL(2,1) DEFAULT 0.6,
    sitemap_pages_changefreq TEXT DEFAULT 'monthly',
    
    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index
CREATE INDEX IF NOT EXISTS idx_seo_settings_site_id ON seo_settings(site_id);

-- Trigger
CREATE TRIGGER update_seo_settings_updated_at 
    BEFORE UPDATE ON seo_settings
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Comments
COMMENT ON TABLE seo_settings IS 'Global SEO settings per site';
COMMENT ON COLUMN seo_settings.separator IS 'Title separator for templates (e.g., | or –)';
COMMENT ON COLUMN seo_settings.title_template_post IS 'Title template for posts (variables: {{title}}, {{siteName}}, {{category}})';

-- ===================================
-- 5. INSERT DEFAULT SEO SETTINGS
-- ===================================
-- Insert default SEO settings for development site
INSERT INTO seo_settings (site_id, site_name, site_tagline)
VALUES (
    '00000000-0000-0000-0000-000000000001',
    'Site de développement',
    'Votre site web'
)
ON CONFLICT (site_id) DO NOTHING;

-- ===================================
-- MIGRATION COMPLETE
-- ===================================
-- Run this migration with:
-- psql -h [host] -U [user] -d [database] -f migration-seo-core.sql
