-- ====================================
-- RESEARCH ENGINE - Database Tables
-- Universal research system using Perplexity
-- ====================================

-- ====================================
-- 1. Research Packs Table
-- ====================================
-- Stores the final validated research for an article topic

CREATE TABLE IF NOT EXISTS research_packs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  site_id UUID NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  content_type_id UUID NOT NULL REFERENCES editorial_content_types(id) ON DELETE CASCADE,
  
  -- Topic/Query
  topic TEXT NOT NULL,
  angle TEXT NULL,
  
  -- Status
  status TEXT NOT NULL DEFAULT 'partial', -- 'partial', 'completed', 'failed'
  attempts_count INT NOT NULL DEFAULT 0,
  
  -- Final validated result
  final_brief_markdown TEXT NULL,
  final_sources JSONB DEFAULT '[]'::jsonb,
  
  -- Metadata
  model_used TEXT NULL,
  total_tokens INT NULL,
  
  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  
  -- Indexes
  CONSTRAINT research_packs_status_check CHECK (status IN ('partial', 'completed', 'failed'))
);

CREATE INDEX IF NOT EXISTS idx_research_packs_site_id ON research_packs(site_id);
CREATE INDEX IF NOT EXISTS idx_research_packs_content_type_id ON research_packs(content_type_id);
CREATE INDEX IF NOT EXISTS idx_research_packs_status ON research_packs(status);
CREATE INDEX IF NOT EXISTS idx_research_packs_created_at ON research_packs(created_at DESC);

COMMENT ON TABLE research_packs IS 'Stores validated research briefs generated by Perplexity for article topics';

-- ====================================
-- 2. Research Attempts Table
-- ====================================
-- Stores each research attempt for audit and debugging

CREATE TABLE IF NOT EXISTS research_attempts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  research_pack_id UUID NOT NULL REFERENCES research_packs(id) ON DELETE CASCADE,
  
  -- Attempt info
  attempt_no INT NOT NULL,
  
  -- Input
  prompt TEXT NOT NULL,
  
  -- Output
  raw_response TEXT NOT NULL,
  
  -- Parsing
  extracted_sources JSONB DEFAULT '[]'::jsonb,
  parsed_payload JSONB DEFAULT '{}'::jsonb,
  
  -- Validation
  gating_report JSONB DEFAULT '{}'::jsonb,
  passed_gating BOOLEAN NOT NULL DEFAULT false,
  
  -- Metadata
  model_used TEXT NULL,
  tokens_used INT NULL,
  duration_ms INT NULL,
  
  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  
  CONSTRAINT research_attempts_unique UNIQUE(research_pack_id, attempt_no)
);

CREATE INDEX IF NOT EXISTS idx_research_attempts_pack_id ON research_attempts(research_pack_id);
CREATE INDEX IF NOT EXISTS idx_research_attempts_attempt_no ON research_attempts(research_pack_id, attempt_no);

COMMENT ON TABLE research_attempts IS 'Stores each research attempt with full context for debugging and audit';

-- ====================================
-- 3. Add research_pack_id to content table
-- ====================================

ALTER TABLE content
  ADD COLUMN IF NOT EXISTS research_pack_id UUID NULL REFERENCES research_packs(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_content_research_pack_id ON content(research_pack_id);

COMMENT ON COLUMN content.research_pack_id IS 'Links article to the research pack used for generation';

-- ====================================
-- 4. Add research config columns to editorial_content_types
-- ====================================

ALTER TABLE editorial_content_types
  ADD COLUMN IF NOT EXISTS research_prompt_template TEXT NULL,
  ADD COLUMN IF NOT EXISTS research_extractor_key TEXT NOT NULL DEFAULT 'article_md',
  ADD COLUMN IF NOT EXISTS research_gating_rules JSONB NOT NULL DEFAULT '{
    "min_sources": 3,
    "min_sections": 2,
    "min_content_length": 500
  }'::jsonb,
  ADD COLUMN IF NOT EXISTS research_max_attempts INT NOT NULL DEFAULT 3,
  ADD COLUMN IF NOT EXISTS research_required BOOLEAN NOT NULL DEFAULT false;

COMMENT ON COLUMN editorial_content_types.research_prompt_template IS 'Template for Perplexity research prompt (uses {{topic}}, {{angle}} placeholders)';
COMMENT ON COLUMN editorial_content_types.research_extractor_key IS 'Key to select which extractor to use (article_md, list_md, review_md, etc.)';
COMMENT ON COLUMN editorial_content_types.research_gating_rules IS 'Dynamic validation rules for research quality';
COMMENT ON COLUMN editorial_content_types.research_max_attempts IS 'Maximum retry attempts for research';
COMMENT ON COLUMN editorial_content_types.research_required IS 'If true, research phase is mandatory before article generation';

-- ====================================
-- Verification queries
-- ====================================

-- Count research packs by status
SELECT status, COUNT(*) as count
FROM research_packs
GROUP BY status;

-- Check editorial_content_types has research config
SELECT 
  key,
  label,
  research_extractor_key,
  research_required,
  research_max_attempts
FROM editorial_content_types
ORDER BY key;

-- ====================================
-- Notes
-- ====================================
-- This migration is safe to run multiple times (idempotent)
-- All ALTER TABLE use IF NOT EXISTS
-- Indexes are created with IF NOT EXISTS
